// <auto-generated />
using System;
using Core.Portal.Infrastructure.SqlServerDatabase.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Core.Portal.Infrastructure.SqlServerDatabase.Contexts.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220814220303_init2")]
    partial class init2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Core.Portal.Infrastructure.SqlServerDatabase.Entities.DepartmentTable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Floor")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = new Guid("24eefa8b-5b9d-42f7-999c-9a54363e7f7e"),
                            Floor = 0,
                            Name = "Department 1"
                        },
                        new
                        {
                            Id = new Guid("121e1d20-1138-4193-8477-cf65e6d238f7"),
                            Floor = 0,
                            Name = "Department 2"
                        });
                });

            modelBuilder.Entity("Core.Portal.Infrastructure.SqlServerDatabase.Entities.EmployeeTable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProgrammingLanguageId")
                        .HasColumnType("int");

                    b.Property<string>("SurName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("ProgrammingLanguageId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("Core.Portal.Infrastructure.SqlServerDatabase.Entities.ProgrammingLanguageTable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ProgrammingLanguages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "python"
                        },
                        new
                        {
                            Id = 2,
                            Name = "java"
                        },
                        new
                        {
                            Id = 3,
                            Name = ".net"
                        },
                        new
                        {
                            Id = 4,
                            Name = "scala"
                        },
                        new
                        {
                            Id = 5,
                            Name = "js"
                        },
                        new
                        {
                            Id = 6,
                            Name = "ruby"
                        },
                        new
                        {
                            Id = 7,
                            Name = "c++"
                        });
                });

            modelBuilder.Entity("Core.Portal.Infrastructure.SqlServerDatabase.Entities.EmployeeTable", b =>
                {
                    b.HasOne("Core.Portal.Infrastructure.SqlServerDatabase.Entities.DepartmentTable", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Portal.Infrastructure.SqlServerDatabase.Entities.ProgrammingLanguageTable", "ProgrammingLanguage")
                        .WithMany("Employees")
                        .HasForeignKey("ProgrammingLanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("ProgrammingLanguage");
                });

            modelBuilder.Entity("Core.Portal.Infrastructure.SqlServerDatabase.Entities.DepartmentTable", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("Core.Portal.Infrastructure.SqlServerDatabase.Entities.ProgrammingLanguageTable", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
